import type { Metadata } from "next";
import StyledComponentsRegistry  from "@/app/lib/registry";
import "./tailwind.global.scss";

export const metadata: Metadata = {
   title: "Home ",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
  children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>
            <StyledComponentsRegistry>
               {children}
            </StyledComponentsRegistry>
         </body>
      </html>
   );
}
