
import type { Metadata } from "next";

export const metadata: Metadata = {
   title: "Home ",
   description: "Generated by create next app",
};
import "./tailwind.global.scss";



export default function RootLayout({
   children,
}: {
  children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>    
            {children}
         </body>
      </html>
   );
}
